mediproject/home/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views

app_name='home'

urlpatterns = [
    path('signin/',views.register,name='register'),
    path('login/',views.userlogin,name='login'),
    path('userdetail/',views.logedin,name='userdetail'),
    path('logedout/',views.logedout,name='logedout'),
    path('uploadimg',views.uploadimg,name='uploadimg')
]

mediproject/mediproject/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('home/',include('home.urls'))
]

mediproject/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserSignupDb(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    mobileNumber=models.CharField(max_length=20)
    age=models.IntegerField()
    choice=[('M','Male'),('F','Female'),('O','Others')]
    gender=models.CharField(choices=choice,null=True,max_length=1)
    
    def __str__(self):
        return self.user.username

class UserImage(models.Model):
    patienteye=models.ImageField(upload_to="retinal_scan",blank=True)
    name=models.ForeignKey(User,on_delete=models.CASCADE)
    dateOfUpload=models.DateField()
    timeOfUpload=models.TimeField()

    def __str__(self):
        return self.name.username

mediproject/home/forms.py
from django import forms
from django.contrib.auth.models import User
from home.models import UserSignupDb,UserImage

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','email','password')
    
    def clean(self):
        cleaned_data=super(UserForm, self).clean()
        password=cleaned_data.get("password")
        confirm_password=cleaned_data.get("confirm_password")
        print("hai1")
        if password != confirm_password:
            print("hai2")
            self.add_error('confirm_password', "Password does not match")

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserSignupDb
        fields=('mobileNumber','age','gender')

class UserImageForm(forms.ModelForm):
    class Meta():
        model=UserImage
        fields=('patienteye',)

mediproject/home/views.py
from django.shortcuts import render
from home.forms import UserForm,UserProfileInfoForm,UserImageForm
from home.models import UserSignupDb
from django.contrib.auth.models import User

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import datetime

def register(request):
    registered=True
    if request.method=="POST":

        userform=UserForm(data=request.POST)
        userInfo=UserProfileInfoForm(data=request.POST)
        if userform.is_valid() and userInfo.is_valid():
            
            user_data=userform.save(commit=False)
            user_data.set_password(user_data.password)

            userprofile=userInfo.save(commit=False)
            user_data.save()
            userprofile.user=user_data
            userprofile.save()
            registered=False
        else:
            return render(request,'signin.html',{'registered':registered,
                                                'userform':userform,
                                                'userinfoform':userInfo}
                                                )            
    
    userform=UserForm
    userinfoform=UserProfileInfoForm
    return render(request,'signin.html',{'registered':registered,
                                            'userform':userform,
                                            'userinfoform':userinfoform})
@login_required
def uploadimg(request):
    uploaded=True
    if request.method=="POST":
        userpic=UserImageForm(data=request.POST)
        if userpic.is_valid():

            saveto=User.objects.get(username=request.user)
            
            usersave=userpic.save(commit=False)
            usersave.name=saveto
            usersave.dateOfUpload=datetime.date.today()
            usersave.timeOfUpload=datetime.datetime.now().time()
            usersave.patienteye=request.FILES['patienteye']
            usersave.save()
            uploaded=False

    return render(request,'upload.html',{'form':UserImageForm,'uploaded':uploaded})

def index(request):
    return render(request,'index.html')


def userlogin(request):

    if request.method=="POST":

        global uname
        username=request.POST.get('username')
        password=request.POST.get('password')
        user_log=authenticate(username=username,password=password)
        if user_log:
            if user_log.is_active:
                login(request,user_log)
                uname=username
                return HttpResponseRedirect(reverse(index))
            else:
                print("User not active")
        else:
            print("Wrong cradentials")

    return render(request,'login.html')

@login_required
def logedin(request):

    global uname
    #shodata=UserSignupDb.objects.get(user = uname)

    shodata = UserSignupDb.objects.get(user=User.objects.get (username=request.user))
    uname=User.objects.get (username=request.user)
    #print(dir(shodata))
    finaldata={'name':uname.username,'age':shodata.age,'mobileNumber':shodata.mobileNumber,'gender':shodata.gender}
    print(finaldata)
    return render(request,'userdetail.html',finaldata)

@login_required
def logedout(request):
    global uname
    logout(request)
    return HttpResponseRedirect(reverse(index))

mediproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" 
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
          crossorigin="anonymous">
</head>
<body>


    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
           <ul class="nav navbar-nav">

            <li><a class="navbar-brand" href="{% url 'index' %}">Index</a>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

            {% if user.is_authenticated %}
              <li><a class="navbar-link" href="{% url 'home:userdetail' %}">details</a></li>
              <li><a class="navbar-link" href="{% url 'home:uploadimg' %}">Upload Image</a></li>
              <li><a class="navbar-link" href="{% url 'home:logedout' %}">logout</a></li>                
            {% else %}
              <li><a class="navbar-link" href="{% url 'home:register' %}">Register</a></li>
              <li><a class="navbar-link" href="{% url 'home:login' %}">Login</a></li>
            {% endif %}
            
          </div>
        </div>
      </nav>

      <div class="container">
        {% block body_block %}
        
        {% endblock %}
      </div>
    
</body>
</html>

mediproject/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>This is index page</h1>
    </div>
{% endblock %}

mediproject/templates/login.html
{% extends 'base.html' %}
{% block body_block %}

    <form action="{% url 'home:login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Enter user name</label>
        <input type="text" name="username" placeholder="John">
        <br/>
        <label for="password">Enter password</label>
        <input type="password" name="password">
        <br/>
        <input type="submit">
    </form>

{% endblock %}

mediproject/templates/signin.html
{% extends 'base.html' %}
{% block body_block %}
        {% if registered %}
            <form method="POST">
                {% csrf_token %}
                {{userform.as_p}}
                {{userinfoform.as_p}}
                <input type="submit" class="btn btn-primary" value="submit">
            </form>
        {% else %}
            <h3>You have been signed in</h3>
            <h4><a href="{% url 'home:login' %}">Login in</a></h4>
        {% endif %}
{% endblock %}

mediproject/templates/upload.html
{% extends 'base.html' %}
{% block body_block %}

    {% if uploaded %}
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" placeholder="Upload">
    </form>
    {% else %}
        <h3>Image uploaded successfully</h3>
        <h3><a href="{% url 'home:uploadimg' %}">Upload again</a></h3>
    {% endif %}
{% endblock %}

mediproject/templates/userdetail.html
{% extends 'base.html' %}
{% block body_block %}
    <h1>User details are</h1>
    <h3>Name:{{name}}</h3>
    <h3>Mobile No:{{mobileNumber}}</h3>
    <h3>Age:{{age}}</h3>
    <h3>Gender:{{gender}}</h3>
    <br/>
{% endblock %}